In [1]:
import pandas as pd

In [15]:
# Selecting Data

# select Columns
df = pd.read_csv("ipl_matches_2026.csv")
df[["city", "venue"]]

              city                                              venue
0        Bengaluru                   M Chinnaswamy Stadium, Bengaluru
1           Mumbai                           Wankhede Stadium, Mumbai
2         Guwahati                Barsapara Cricket Stadium, Guwahati
3   New Chandigarh  Maharaja Yadavindra Singh International Cricke...
4          Lucknow  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
..             ...                                                ...
69         Kolkata                              Eden Gardens, Kolkata
70      Dharamsala  Himachal Pradesh Cricket Association Stadium, ...
71  New Chandigarh  Maharaja Yadavindra Singh International Cricke...
72  New Chandigarh  Maharaja Yadavindra Singh International Cricke...
73       Ahmedabad                   Narendra Modi Stadium, Ahmedabad

[74 rows x 2 columns]

In [16]:
# select rows (label and index based) - loc & iloc

# label
df.loc[1]
df.loc[0:2]  # [start idx: end idx] end index is inclusive here

# index based
df.iloc[0:2] # end idx exlusive here

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,2026-03-28,2026,Bengaluru,"M Chinnaswamy Stadium, Bengaluru",Sunrisers Hyderabad,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,201,9,...,6,JA Duffy,J Srinath,J Madanagopal,UV Gandhe,R Pandit,A Bengeri,20,"TM Head, Abhishek Sharma, Ishan Kishan, Nithis...","JA Duffy, PD Salt, V Kohli, D Padikkal, RM Pat..."
1,2026-03-29,2026,Mumbai,"Wankhede Stadium, Mumbai",Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,220,4,...,6,SN Thakur,Shakti Singh,Anish Sahasrabudhe,MV Saidharshan Kumar,Nitin Menon,Vinod Seshan,20,"Kartik Tyagi, AM Rahane, FH Allen, C Green, A ...","JJ Bumrah, RD Rickelton, RG Sharma, SA Yadav, ..."

In [22]:
# select rows and columns

df.loc[0, "city"]
df.loc[0:2, ["team1", "team2"]]

# df.iloc[0, "city"] # error
df.iloc[0:2, 2] # 2 -> index of city in columns

0    Bengaluru
1       Mumbai
Name: city, dtype: object

In [25]:
# select single scalar value - at(labels) & iat(idx)

df.at[0, "city"]
df.iat[0, 2]

'Bengaluru'

In [33]:
# copy vs view

cities = df["city"]
# cities[0] = "America" # it actually changes the original df 

# so when ever we want to create a copy 
cities = df["city"].copy()
cities[0] = "America"  # original is df is not changed
cities

0            America
1             Mumbai
2           Guwahati
3     New Chandigarh
4            Lucknow
           ...
69           Kolkata
70        Dharamsala
71    New Chandigarh
72    New Chandigarh
73         Ahmedabad
Name: city, Length: 74, dtype: object

In [34]:
df

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,2026-03-28,2026,Bengalore,"M Chinnaswamy Stadium, Bengaluru",Sunrisers Hyderabad,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,201,9,...,6,JA Duffy,J Srinath,J Madanagopal,UV Gandhe,R Pandit,A Bengeri,20,"TM Head, Abhishek Sharma, Ishan Kishan, Nithis...","JA Duffy, PD Salt, V Kohli, D Padikkal, RM Pat..."
1,2026-03-29,2026,Mumbai,"Wankhede Stadium, Mumbai",Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,220,4,...,6,SN Thakur,Shakti Singh,Anish Sahasrabudhe,MV Saidharshan Kumar,Nitin Menon,Vinod Seshan,20,"Kartik Tyagi, AM Rahane, FH Allen, C Green, A ...","JJ Bumrah, RD Rickelton, RG Sharma, SA Yadav, ..."
2,2026-03-30,2026,Guwahati,"Barsapara Cricket Stadium, Guwahati",Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,127,10,...,8,N Burger,V Narayan Kutty,HDPK Dharmasena,M Krishnadas,VK Sharma,K Swaroopanand,20,"SV Samson, RD Gaikwad, A Mhatre, MW Short, SN ...","YBK Jaiswal, V Suryavanshi, Dhruv Jurel, R Par..."
3,2026-03-31,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Gujarat Titans,Punjab Kings,Punjab Kings,field,162,6,...,3,C Connolly,Prakash Bhatt,Abhijit Bhattacharya,A Totre,KN Ananthapadmanabhan,P Joshi,20,"M Prasidh Krishna, B Sai Sudharsan, Shubman Gi...","YS Chahal, Priyansh Arya, P Simran Singh, C Co..."
4,2026-04-01,2026,Lucknow,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Delhi Capitals,Delhi Capitals,field,141,10,...,6,Sameer Rizvi,J Srinath,R Pandit,UV Gandhe,J Madanagopal,A Bengeri,20,"MR Marsh, RR Pant, AK Markram, A Badoni, N Poo...","T Natarajan, KL Rahul, P Nissanka, N Rana, Sam..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,2026-05-24,2026,Kolkata,"Eden Gardens, Kolkata",Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,203,5,...,0,Kuldeep Yadav,IR Siddiqui,K Swaroopanand,HAS Khalid,SJ Nogajski,M Krishnadas,20,"Kuldeep Yadav, Abishek Porel, KL Rahul, SU Par...","SP Narine, AM Rahane, FH Allen, MK Pandey, C G..."
70,2026-05-26,2026,Dharamsala,"Himachal Pradesh Cricket Association Stadium, ...",Royal Challengers Bengaluru,Gujarat Titans,Gujarat Titans,field,254,5,...,0,RM Patidar,J Srinath,J Madanagopal,VK Sharma,Nitin Menon,KN Ananthapadmanabhan,20,"R Shepherd, VR Iyer, V Kohli, D Padikkal, RM P...","K Khejroliya, B Sai Sudharsan, Shubman Gill, J..."
71,2026-05-27,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,243,8,...,0,V Suryavanshi,V Narayan Kutty,AT Holdstock,UV Gandhe,R Pandit,SJ Nogajski,20,"YBK Jaiswal, V Suryavanshi, Dhruv Jurel, R Par...","PP Hinge, Abhishek Sharma, TM Head, Ishan Kish..."
72,2026-05-29,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,bat,214,6,...,7,Shubman Gill,Prakash Bhatt,R Pandit,SJ Nogajski,AT Holdstock,UV Gandhe,20,"TU Deshpande, YBK Jaiswal, V Suryavanshi, Dhru...","Mohammed Siraj, B Sai Sudharsan, Shubman Gill,..."
73,2026-05-31,2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,155,8,...,5,V Kohli,J Srinath,KN Ananthapadmanabhan,Nitin Menon,J Madanagopal,VK Sharma,20,"M Prasidh Krishna, B Sai Sudharsan, Shubman Gi...","JA Duffy, VR Iyer, V Kohli, D Padikkal, RM Pat..."