In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("raw_data.csv")
df2 = df.copy()

# transforming Data -> Feature Engineering

# apply()
df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 50000 else "10%")

# map()
gender_map = {"Male": "M", "Female": "F", "Unknown": "U"}
df2["gender"] = df2["gender"].map(gender_map)

# replace(old, new)
df2["country"] = df2["country"].replace("USA", "United States")

# assign()
df2 = df2.assign(new_income = df2["income"] * 1.1)
df2

    id          name   age        country gender   income  tax  new_income
0    1      John Doe  29.0  United States      M  55000.0  20%     60500.0
1    1      John Doe  29.0  United States      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN         Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0          Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0          China      M  51000.0  20%     56100.0
6    6           NaN  45.0          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United States    NaN  58000.0  20%     63800.0

In [16]:
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax", "New_income"]

# rename()
df2.rename(columns = {"Income": "Salary"})
df2.rename(index = {1 : "First"})

# sort_values()
df2.sort_values("Income")
df2.sort_values("Income", ascending = False)

df2["Age"] = df2["Age"].fillna(18)
sorted_df = df2.sort_values(["Income", "Age"])

sorted_df.sort_index()

    Id          Name   Age        Country Gender   Income  Tax  New_income
0    1      John Doe  29.0  United States      M  55000.0  20%     60500.0
1    1      John Doe  29.0  United States      M  55000.0  20%     60500.0
2    2    Jane Smith  18.0         Canada      F  62000.0  20%     68200.0
3    3          Alex  18.0  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0          Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0          China      M  51000.0  20%     56100.0
6    6           NaN  45.0          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz  18.0         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United States    NaN  58000.0  20%     63800.0

In [17]:
# reset
sorted_df.reset_index()
sorted_df.reset_index(drop = True)

# ranking
# sorted_df["Ranking"] = sorted_df["Income"].rank(ascending = False, method = "dense")

sorted_df[["Id", "Name", "Age", "Gender","Country", "Income", "New_income", "Tax"]]

    Id          Name   Age Gender        Country   Income  New_income  Tax
9    9   Carlos Ruiz  18.0      M         Mexico  45000.0     49500.0  10%
3    3          Alex  18.0      U  United States  47000.0     51700.0  10%
5    5        Li Wei  27.0      M          China  51000.0     56100.0  20%
0    1      John Doe  29.0      M  United States  55000.0     60500.0  20%
1    1      John Doe  29.0      M  United States  55000.0     60500.0  20%
10  10   Emily Davis  31.0    NaN  United States  58000.0     63800.0  20%
2    2    Jane Smith  18.0      F         Canada  62000.0     68200.0  20%
8    8    Rachel Lee  29.0      F  United States  62000.0     68200.0  20%
7    7    Ahmed Khan  38.0      M            NaN  68000.0     74800.0  20%
6    6           NaN  45.0      F          India  73000.0     80300.0  20%
4    4  Maria Garcia  34.0      F          Spain      NaN         NaN  10%